### ISSUE TITLE
Using  media branch

### ISSUE THREAD

**Issue by mesa57** [jgeusebroek/docker-spotweb#1]
The media branch is terrible behind the non media master branch and is missing many essential updates.
It also is not maintained any more.

**Comment by jgeusebroek** [comment]
Thanks, it's been a while since I looked at it. At that point I thought the media branche was newer.
I will test if it can be done without any database problems and then change to master.

**Comment by jgeusebroek** [comment]
Fixed! 0c86206459b77ab4632b9366b3bc0e3d9d52574b

**Comment by mesa57** [comment]
Nice, thx. Synology users will be gratefull :smile:
