### ISSUE TITLE
Add environment variable for base href

### ISSUE THREAD

**Issue by neographikal** [jgeusebroek/docker-spotweb#10]
I'm running spotweb behind a reverse proxy that serves it through TLS/SSL. It doesn't figure that out so css/js is broken. Would be nice if the URL could be set through an env variable. :)

**Comment by jgeusebroek** [comment]
Sorry for the late reply. This is not really related to the docker image, but more so of Spotweb itself.

https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting has a possible solution.
