### ISSUE TITLE
Chowning of the spotweb folder

### ISSUE THREAD

**Issue by riemers** [jgeusebroek/docker-spotweb#11]
Hi there, i am in the middle of jumping over to this image since i have a very old one that is pretty much broken. 

So far its been running for 15 minutes and it has not finished the chown on the spotweb folder. Mostly because i have my cache folder mounted on the filesystem. That folder is 6.5gb and has a ton of folders too. At some point keeping the cache sounded like a good idea but now it leaves me with 2 questions.

* do i really need to keep the cache folder? After all, its only for an image of a post right?
* and if its handy to have, is there something we can do with the chown?

I don't think there is an option inside docker to detect if a folder is mounted from outside, that way we could ignore it. What are your thoughts?

**Comment by riemers** [comment]
Just as a extra feedback.

The '' quotes on the cron examples can be left since if you copy those the crontab will fail. (easy mistake)
If you have your spotweb in /spotweb, one needs to change the virtualhost to point to /var/www instead. You could add a environment option that does a inline sed to remove /spotweb. (could do a PR but have no time to test, kids screaming now 👶)

**Comment by jgeusebroek** [comment]
Thanks for your feedback. You do not need to mount your cache folder. I don't at least :)

> If you have your spotweb in /spotweb, one needs to change the virtualhost to point to /var/www instead.

I don't really understand what you mean, the image has it in it's own specified folder and everything works fine? 

What's the cron error you are receiving?

**Comment by riemers** [comment]
i have my spotweb in /spotweb, not as spotweb.domain.com hence the need for /spotweb.

The cron error if you add '' in the line is that it cannot parse it. So in the example if you copy paste it it won't work. Not a showstopper, but no harm done to tell right.

My cache folder was huge at some point though, perhaps its better to just clean it every now and then to keep the speed in it. Not like you cannot redownload an image unless it points to a expired link.

**Comment by jgeusebroek** [comment]
I clarified cron usage in the readme. Thanks!
