### ISSUE TITLE
Cronjobs don't get added on container creation

### ISSUE THREAD

**Issue by markheloking** [jgeusebroek/docker-spotweb#12]
For some reason even after adding SPOTWEB_CRON_RETRIEVE='*/15 * * * *' to the environment, the crontab for all users is still empty after the container spins up. This leads to the container not actually retreiving spots.

**Comment by markheloking** [comment]
The issue is that the suggested crontab syntax in the docs seems to be invalid (at least for docker-composer yml files). It should be without apostrophe's and quotation marks like so: `SPOTWEB_CRON_RETRIEVE=*/2 * * * *`.

**Comment by jgeusebroek** [comment]
I can't replicate this. Since you closed it, was it perhaps a user error?

**Comment by markheloking** [comment]
If you literally add `SPOTWEB_CRON_RETRIEVE='*/15 * * * *'` as an environment variable (as suggested in the readme), crontab will error out and the cronjob will never be added/running. The correct syntax is `SPOTWEB_CRON_RETRIEVE=*/2 * * * *` as I stated earlier. The error isn't so much in the image itself, rather it's a mistake in the readme.

**Comment by jgeusebroek** [comment]
What is the output of `crontab -l` within your container?

Have a look at my output below (using asciinema), this seems to be fine. TBH I don't use the crontab within the container myself. But I can't see anything wrong with it.

https://asciinema.org/a/vBMdCIfYKsnm6WRnpHHOe4gle

**Comment by markheloking** [comment]
I'd swear I have copied the command directly from the readme, but the readme clearly states `-e 'SPOTWEB_CRON_RETRIEVE=*/15 * * * *'` and not `-e SPOTWEB_CRON_RETRIEVE='*/15 * * * *'`. Strange. User error nonetheless.

**Comment by jgeusebroek** [comment]
I changed the README. That's why ;) However it also works for me with using the other syntax. I couldn't replicate the problem (see below). Maybe it's because I'm using a different Docker version (18.09.1).

[![asciicast](https://asciinema.org/a/gz3EIU8ueYNTQrxrSGU3gr078.svg)](https://asciinema.org/a/gz3EIU8ueYNTQrxrSGU3gr078)
