### ISSUE TITLE
Make Spotweb updates possible

### ISSUE THREAD

**Issue by Groofster** [jgeusebroek/docker-spotweb#13]
Is there any way to implement a way of updating Spotweb ? Now we have to wait for either a new image, build the image from the dockerfile or do some git voodoo to update the Spotweb install. For example, is it possible to leave the .git file in the install so we can git pull ? Or is there a specific reason for remving it ?

The reason I ask is because there is a 'serious' issue in the currently packaged version of Spotweb (Merge pull request #410) that is making Spotweb rather useless for searches by IMDB Id. And of course making the changes manually is possible but that makes rebuilding docker stacks and such kinda difficult.

**Comment by jgeusebroek** [comment]
One of the principles of Docker containers is that an image is immutable. They are not meant to be changed, but rather update (rebuild) the container if a change is needed.

In a perfect world I would check for changes in the GitHub repo and rebuild the image automatically when a change is made, or a new version is released. I don't have this setup right now, but I do have weekly new builds. 

You always have the choice to rebuild the image yourself. It's very easy, just clone the docker-spotweb repo and run ./build.sh.

So you have two options. Wait for the new (weekly) auto build, or build it yourself.

Bu now that you made me aware of this hotfix, I forced a rebuild myself. The updated image is on Docker Hub :)

**Comment by Groofster** [comment]
First of all, thank you for taking the time to react (and updating the image). I totally agree with the docker stance on immutability, I really enjoy the advantages it brings. But I do think that if a "simple solution" is possible and you make it an opt-in, it can make life for some users easier. And as you probably know, "nee heb je, ja kun je krijgen", so I thought, why not just ask.

Thanks again for great image, have been enjoying it for quite some time now.
