### ISSUE TITLE
Unsuccessful install with "Permanent installation" on Synology

### ISSUE THREAD

**Issue by cnoork** [jgeusebroek/docker-spotweb#15]
After I have done "install.php" all looks fine but when I try to make it permanent it looks like the environment settings are not parsing to the container. What is going wrong and how can I debug to find the cause. I run the container on a Synology with intel processor. Here is also my environment page and the result in the browser:

![2019-05-30 15_46_50-snoek - Synology DiskStation](https://user-images.githubusercontent.com/17862084/58637157-3686a100-82f2-11e9-9557-3daa5df55d70.jpg)

![2019-05-30 15_49_34-snoek - Synology DiskStation](https://user-images.githubusercontent.com/17862084/58637361-a2690980-82f2-11e9-95b6-8dbfd46808c7.jpg)

![2019-05-30 15_45_34-192 168 10 10_81](https://user-images.githubusercontent.com/17862084/58637174-3c7c8200-82f2-11e9-85be-a8de0b028cb5.jpg)

**Comment by cnoork** [comment]
Found an error which I overlooked before... But still not a clue what the issue is.

![image](https://user-images.githubusercontent.com/17862084/58663698-58e9e000-832d-11e9-9af3-8869f4b67d9e.png)

**Comment by cnoork** [comment]
Found 1 think and that is that I was using MariaDB 10 which is using port 3307, changed it to MariaDB 5.5 which is running on 3306. Unfortunately after successful install it still complains about "Unable to connect to database". I can see that the tables are created with phpMyAdmin. When someone has a suggestion it would be nice. Mean while I will go further with searching and will update when I have news. By the way, do not know if this is relevant, I remap the port to another one, I run already a web server on port 80.

**Comment by cnoork** [comment]
The link for dbsettings.inc.php had root rights, that should not be a problem but when I change the script "entrypoint.sh" the "ln-s " into "cp -p" for that file my spotweb is working. Is this a known issue or do I something wrong?

        # ln -s /config/dbsettings.inc.php /var/www/spotweb/dbsettings.inc.php
        cp -p /config/dbsettings.inc.php /var/www/spotweb/dbsettings.inc.php

For now I can run spotweb but would like to do updates in the future and thereby it needs to be running out of the box ;-)

**Comment by jgeusebroek** [comment]
Glad you figured it out yourself :) First of all, I would recommend to remove the screenshot of the failure message, it includes your password. 

Second, the database password does not match the password you have in your docker environment.
Running spotweb on another port is not a problem.

The error you see when it first tries to save the database config is normal, it is mentioned in the documentation.

To start over, just delete your docker-spotweb/config directory, set the correct environment variables and start over. It should work.

**Comment by cnoork** [comment]
Thanks for the feedback. For the settings and start over I did that several times and could not succeed on that. It keep telling that it has no rights on the file. For now I have a workaround which is easy to implement. I wonder if I am really the only one with this issue.

**Comment by timosnel** [comment]
Running into the exact same issue here. Getting the message:

`No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.`

I can connect to mysql from inside the container, it seems to be a permission issue on the symlink created for the `dbsettings.inc.php`. @cnoork did you ever fix this without creating your own image?

**Comment by cnoork** [comment]
I was forgotten what the cause was, but now I read your comment I remember that I removed the symlink and placed the file on that location. That did solve my problem.
