### ISSUE TITLE
Needs another update after installation

### ISSUE THREAD

**Issue by slootjes** [jgeusebroek/docker-spotweb#2]
```
Notice: Undefined index: xsrfsecret in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 62

Notice: Undefined index: settingsversion in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 62
Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window
```

It was solved after running the upgrade script, would be nice if this was done automatically.

**Comment by jgeusebroek** [comment]
Thanks for reporting. The thing is, that 'bin/upgrade-db.php' is already run on every start.
https://github.com/jgeusebroek/docker-spotweb/blob/master/entrypoint.sh#L27

Are you sure you where running the latest image? I can't really explain this.

**Comment by itmagix** [comment]
Seeing the same issue, to fix this I added the following into the entrypoint.sh:

[code]
        # Run database update
        /usr/local/bin/php /var/www/html/bin/upgrade-db.php
        echo 'Waiting for 5 seconds en run a database update to get rid of "Notice: Undefined index: xsrfsecret" and "Notice: Undefined index: settingsversion" message'
        sleep 5
        /usr/local/bin/php /var/www/html/bin/upgrade-db.php
else
        echo -e "\nWARNING: You have no database configuration file, either create $DATA/dbsettings.inc.php or restart this container with the correct environment variables to auto generate the config.\n"
fi
[/code]

**Comment by jgeusebroek** [comment]
Fixed https://github.com/jgeusebroek/docker-spotweb/commit/586dd9960483793caff0e65590d4a07aa6ac7c85.
