### ISSUE TITLE
Failed to retrieve Article

### ISSUE THREAD

**Issue by justinw78** [jgeusebroek/docker-spotweb#21]
After install i get on the most of the spots the next error:

getHeader(): Failed to retrieve article: getHeader(): Failed to retrieve article: getHeader(): Failed to retrieve article: getHeader(): Failed to retrieve article: SpotWeb v0.68.32.33 on PHP v7.4.3 crashed object(NntpException)#36 (11) { ["_response":"NntpException":private]=> string(18) "Not in a newsgroup" ["message":protected]=> string(63) "No newsgroup has been selected [response: "Not in a newsgroup"]" ["string":"CustomException":private]=> NULL ["code":protected]=> int(412) ["file":protected]=> string(60) "/var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php" ["line":protected]=> int(2281) ["trace":"Exception":private]=> array(11) { [0]=> array(5) { ["file"]=> string(60) "/var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php" ["line"]=> int(1189) ["function"]=> string(10) "throwError" ["class"]=> string(24) "Net_NNTP_Protocol_Client" ["type"]=> string(2) "->" } [1]=> array(5) { ["file"]=> string(51) "/var/www/spotweb/vendor/spotweb/nntp/src/Client.php" ["line"]=> int(516) ["function"]=> string(7) "cmdHead" ["class"]=> string(24) "Net_NNTP_Protocol_Client" ["type"]=> string(2) "->" } [2]=> array(5) { ["file"]=> string(59) "/var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php" ["line"]=> int(325) ["function"]=> string(9) "getHeader" ["class"]=> string(15) "Net_NNTP_Client" ["type"]=> string(2) "->" } [3]=> array(5) { ["file"]=> string(59) "/var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php" ["line"]=> int(338) ["function"]=> string(9) "getHeader" ["class"]=> string(20) "Services_Nntp_Engine" ["type"]=> string(2) "->" } [4]=> array(5) { ["file"]=> string(59) "/var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php" ["line"]=> int(338) ["function"]=> string(9) "getHeader" ["class"]=> string(20) "Services_Nntp_Engine" ["type"]=> string(2) "->" } [5]=> array(5) { ["file"]=> string(59) "/var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php" ["line"]=> int(338) ["function"]=> string(9) "getHeader" ["class"]=> string(20) "Services_Nntp_Engine" ["type"]=> string(2) "->" } [6]=> array(5) { ["file"]=> string(64) "/var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php" ["line"]=> int(194) ["function"]=> string(9) "getHeader" ["class"]=> string(20) "Services_Nntp_Engine" ["type"]=> string(2) "->" } [7]=> array(5) { ["file"]=> string(71) "/var/www/spotweb/lib/services/Providers/Services_Providers_FullSpot.php" ["line"]=> int(46) ["function"]=> string(12) "readFullSpot" ["class"]=> string(25) "Services_Nntp_SpotReading" ["type"]=> string(2) "->" } [8]=> array(5) { ["file"]=> string(66) "/var/www/spotweb/lib/services/Actions/Services_Actions_GetSpot.php" ["line"]=> int(28) ["function"]=> string(13) "fetchFullSpot" ["class"]=> string(27) "Services_Providers_FullSpot" ["type"]=> string(2) "->" } [9]=> array(5) { ["file"]=> string(46) "/var/www/spotweb/lib/page/SpotPage_getspot.php" ["line"]=> int(23) ["function"]=> string(11) "getFullSpot" ["class"]=> string(24) "Services_Actions_GetSpot" ["type"]=> string(2) "->" } [10]=> array(5) { ["file"]=> string(26) "/var/www/spotweb/index.php" ["line"]=> int(127) ["function"]=> string(6) "render" ["class"]=> string(16) "SpotPage_getspot" ["type"]=> string(2) "->" } } ["previous":"Exception":private]=> NULL ["string":"Exception":private]=> string(0) "" ["_detail"]=> string(30) "No newsgroup has been selected" ["_code"]=> int(412) } No newsgroup has been selected [response: "Not in a newsgroup"]

Is there something wrong in the settings?

I hope you can help me with this problem.

Greetings justin

**Comment by jgeusebroek** [comment]
To be honest I'm not sure. I haven't seen this before. My first guess would be an issue with your usenet provider. Try starting over with the configuration (deleting the old), and make sure the first sync is finished.

**Comment by proddy** [comment]
I'm not seeing these issues either.

**Comment by justinw78** [comment]
Thnx for the answere.  I did the installation over and over ;)  But the solution wasn´t in spotweb but in SABnzbd. There the connections were set above the 10 and the connection wont accept it. So i have put it down and it works for now.

Thnx for your time:)

greetings Justin
