### ISSUE TITLE
cronjob  issue

### ISSUE THREAD

**Issue by Spotter2011** [jgeusebroek/docker-spotweb#24]
I'm trying to set up a job but apparently I'm doing something wrong you can help me don't get it

[~] # docker run -d --name=spotwebretrieve  --rm -p 80:80 -e TZ='Europe/Amsterdam'  -e SPOTWEB_CRON_RETRIEVE='*/15 * * * *' jgeusebroek/spotweb
1768c2512172578592b6817a06b3e5e16d91181cbb3df513fa4579087296f233
docker: Error response from daemon: driver failed programming external connectivity on endpoint spotwebretrieve (93d5e4ebbd320208d8c3fad994969784881dd6d511ee751375ee7c1fb68d8848): listen tcp 0.0.0.0:80: bind: address already in use.

**Comment by jgeusebroek** [comment]
This doesn't have anything to do with the cronjob. There is already a service bound to port 80. Try another port, or stop the service that is already running on port 80.
