### ISSUE TITLE
Geen afbeeldingen

### ISSUE THREAD

**Issue by roeiegans** [jgeusebroek/docker-spotweb#28]
Hallo,

Ik heb docker draaien met jullie image op een Synology. Op zich werkt e.e.a. prima. Alleen krijg ik geen afbeeldingen te zien bij de spots. Ik heb daar wel op gegoogled en kom wat zaken tegen, zoals dit:

http://www.synology-forum.nl/spotweb/na-upgrade-naar-dsm-5-haalt-spotweb-geen-plaatjes-meer-op/

Als dit al de oplossing is voor mijn Docker installatie, dan zou ik niet weten hoe ik dit zou moeten doen binnen Docker. Kunnen jullie me hiermee helpen? Want ik neem aan dat dit dan zal moeten worden opgelost met environmental variables.

**Comment by Alootje** [comment]
I have a similar issue. In my case sometimes images refuse to load, while for other spots they load perfectly fine.

**Comment by jgeusebroek** [comment]
While browsing Spotweb try running on the server:
`docker exec -ti spotweb tail -f /var/log/apache2/error.log`

Can you paste the output?

**Comment by Alootje** [comment]
I had to update to:
`docker exec -ti spotweb tail -f /var/log/nginx/error.log`

I browsed spots with working images and without. Unfortunately nothing comes up in the errror log.
If I double click the spinning wheel with 'Loading image':
![image](https://user-images.githubusercontent.com/20538605/153274854-249031c6-9862-40c2-807d-cf9f871137d0.png)

If I right-click --> show image in new tab I see ~1/3 of the image.

**Comment by jgeusebroek** [comment]
Are you sure you are running my image? And if so, what version? NginX is not used in my image.

`docker image -a `

**Comment by Alootje** [comment]
Well, I'm sure, it's not your image. :$ 
Apperantly I'm using the image of Erik de Vries... I mixed things up, I was under the impression that I was using your image, my apologies.

I will setup your image and see whether that has the same issue. I'll report back, probably somewhere in the weekend.

**Comment by jgeusebroek** [comment]
Awesome, thanks for the feedback! I'm going to close this issue.
