### ISSUE TITLE
Change port 81 on docker container

### ISSUE THREAD

**Issue by jpdsceu** [jgeusebroek/docker-spotweb#29]
Hi there,

It seems like port 81 is hardcoded in either Apache config or Spotweb itself.
Would it be possible to add a environment to support using a different port?

Next to this, PUID and GUID isn't being used. When using the volume, user 33 is set instead of the one added in the environment.

Thanks.

Cheers,

**Comment by jgeusebroek** [comment]
Hi,

There is no support for PUID and GUID, I don't see a need for this at this point. You are welcome to provide a pull request should you wish this to be added.

Furthermore you can change the port to anything you'd like by changing the docker portmapping. 81:80, 8080:80 etc.
[https://docs.docker.com/config/containers/container-networking/#published-ports](url)

Have a nice day!
