### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by itmagix** [jgeusebroek/docker-spotweb#3]
Hi Jeroen,

Maybe i'm overseeing something but how do I get a admin user to configure stuff in Spotweb? When I create a user in de main screen it will be a regular user.

Thanks in advance.

Maikel

**Comment by jgeusebroek** [comment]
Hi Maikel,

You should be able to run the setup at http://<yourhost>/install.php, just like you would if you where to install the 'non' docker version.

Have a look at https://github.com/spotweb/spotweb/wiki should you have install issues. And don't forget the cron :)

Thanks, I updated the readme :) 

Jeroen

**Comment by itmagix** [comment]
Hi Jeroen,

I'm aware of the installer and did try it, but I receive this message after installing:

     Spotweb has already been setup. If you want to run this wizard again, please remove the file 'dbsettings.inc.php' 

     Please correct the errors in below form and try again

In the **Usage** section in the Readme you mis a trailing **\** so copy/paste won't go well.

Thanks for your reply!

Maikel

**Comment by jgeusebroek** [comment]
Thanks for the feedback! I updated the README with initial installation information. You should remove all the tables in your current database and follow the guide.

Let me know if this helps.

Jeroen

**Comment by magnu5** [comment]
do this to reset the admin password to "spotweb":
`docker exec -it spotweb bash`
then navigate to `/var/www/spotweb` and do this:
`php bin/upgrade-db.php --reset-password admin`
