### ISSUE TITLE
Language only English?

### ISSUE THREAD

**Issue by MrHappy** [jgeusebroek/docker-spotweb#32]
Is it my installation or is there something wrong?
Despite selecting Dutch as language everything shows in English...

**Comment by MrHappy** [comment]
Seems to be a missing nl_NL-locale... After installing it (in the image) it shows Dutch off and on...  So does not look like a complete fix...

**Comment by mesa57** [comment]
The installation of locale nl_NL.UTF8 should be added to the docker file. 
It does not help if the host has locale nl_NL.UTF8

**Comment by MrHappy** [comment]
@jgeusebroek Kun je deze locale toevoegen aan de docker-file? Can you add this locale to the docker-file?

**Comment by jgeusebroek** [comment]
@mesa57 voldoet het om alleen die locale te generen? Hoeft dus niet default te zijn?

**Comment by MrHappy** [comment]
@jgeusebroek en @mesa57 ik heb de volgende stappen gedaan (in de docker image) om de Nederlandse vertaling zichtbaar te krijgen:
`apt update`
`apt install locales`
# verwijderd voor nl_NL.UTF8 in /etc/locale.gen
`locale-gen nl_NL.UTF8`
Wanneer ik de andere nl_NL erbij installeer krijg ik een error dat SABNZBd 1 parameter verwacht.

**Comment by mesa57** [comment]
> 
> 
> @mesa57 voldoet het om alleen die locale te generen? Hoeft dus niet default te zijn?

@jgeusebroek : that's correct. Spotweb will select nl_NL.UTF8 via the php locales function.
There are examples on the net how to remove the # before the locale in /etc/locale.gen with sed (stream editor).
Also the locale-gen has no parameters, it just takes file /etc/locale.gen default as input.

**Comment by jgeusebroek** [comment]
Fixed with 584bd4fb9e28d47a04ce04d37e4e59d751dab545. It works for me. Can you confirm?

**Comment by mesa57** [comment]
I would like to, but I have no idea how. Currently I use portainer / docker hub to install images and containers. That's how far my docker usage knowlegde goes.

**Comment by MrHappy** [comment]
renamed my locale.gen in the container and updated the stack. My renamed locale.gen was gone and the locale.gen was there (with the nl_nl enabled). So it seems to work fine!
Thanks!

**Comment by mesa57** [comment]
Changing it inside you're container does not test the change that @jgeusebroek did.

**Comment by mesa57** [comment]
Ok, found an updated image on docker hub : jgeusebroek/docker-spotweb
Pulled that one and started it.

![afbeelding](https://user-images.githubusercontent.com/6350469/127739623-146e5632-9016-476c-be6b-9bccfa1737ff.png)

That one works fine ! 😄 👍 
You can close the issue.

**Comment by jgeusebroek** [comment]
Awesome, thanks for letting me know!

**Comment by MrHappy** [comment]
> Changing it inside you're container does not test the change that @jgeusebroek did.

That's why I updated the stack, it pulled the new version ;)
@jgeusebroek Thanks again! :+1:
