### ISSUE TITLE
Support for different database ports

### ISSUE THREAD

**Issue by DracoMilesX** [jgeusebroek/docker-spotweb#4]
Currently the container only allows port 3306 to be used. It would be great if we can allow other ports to used as well.

**Comment by jgeusebroek** [comment]
Last time I checked, unfortunately Spotweb doesn't support a different port, it was hardcoded in the source.

**Comment by DracoMilesX** [comment]
Well that's a shame to hear. Guess I will close this one. Thanks for the information.
