### ISSUE TITLE
Apply hardening to Apache webserver

### ISSUE THREAD

**Issue by Xitro01** [jgeusebroek/docker-spotweb#41]
As can be seen in this issue, I've found a XSS in the spotweb application:
https://github.com/spotweb/spotweb/issues/718

Also I found a couple of other security issues related to the used Apache webserver of this docker, I assume that this has nothing to do with the core application, but with how this docker has been configured.

My advice is to harden the used Apache server (configuration):
- Remove version information.
- Do not allow directory listings.
- Add the X-Frame-Options or Content-Security-Policy security header.
- Remove .git file from root webfolder.

**Comment by jgeusebroek** [comment]
Thanks, I will have a look ASAP.

**Comment by jgeusebroek** [comment]
I've add some hardening, can you please test again?

**Comment by Xitro01** [comment]
> I've add some hardening, can you please test again?

Just updated it, testing it now.

**Comment by Xitro01** [comment]
All good now! Only thing I would like to add is the XSS security header (should've mentioned that straight away):
X-XSS-Protection: 1; mode=block

These changes give the web application the basic security hygiene that every application should have.

**Comment by jgeusebroek** [comment]
Thanks for the heads up! I've added the XSS protection header.

The build checks out the master branch, I can't find any version tags in the repo.
