### ISSUE TITLE
SSL operation failed with code 1

### ISSUE THREAD

**Issue by Smiggel** [jgeusebroek/docker-spotweb#43]
Having trouble connection to Eweka using SSL. I can not retrieve spots and see this output in the terminal:

PHP Warning:  stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729

**Comment by jgeusebroek** [comment]
That's weird. What hostname are you using? The docker images uses the latest CA root certificates.

**Comment by proddy** [comment]
Eweka and SSL works for me

![image](https://user-images.githubusercontent.com/1230712/144303365-f470a123-8229-412f-afdb-fcc1497fae0b.png)

**Comment by jgeusebroek** [comment]
And if you disable verify name; does it work?

**Comment by proddy** [comment]
> And if you disable verify name; does it work?

yes

**Comment by jgeusebroek** [comment]
Thanks it was meant for @Smiggel . I should have been more clear :)

**Comment by Smiggel** [comment]
Whoops. Sorry for the late reply. I did not get any notifications. :-)

I tried it again today. 

> Removing Spot information which is beyond retention period,, done
> Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
> Retrieving new Spots from server news.eweka.nl...
> PHP Warning:  stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
> error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729
> PHP Warning:  stream_socket_client(): Failed to enable crypto in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729
> PHP Warning:  stream_socket_client(): Unable to connect to ssl://news.eweka.nl:563 (Unknown error) in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729
> SpotWeb v0.68.33.34 on PHP v8.0.13 crashed
> 
> Fatal error occured while connecting to the newsserver:
>   (-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]
> 
> 
> #0 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(143): Services_Nntp_Engine->connect()
> #1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(118): Services_Nntp_Engine->selectGroup()
> #2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(298): Services_Retriever_Base->connect()
> #3 /var/www/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
> #4 {main}
> 
> Finished retrieving spots
<img width="495" alt="Schermafbeelding 2021-12-02 om 17 19 19" src="https://user-images.githubusercontent.com/1825953/144461150-ccc38e40-2188-4954-9d24-eac4ec6aadbe.png">
.

**Comment by jgeusebroek** [comment]
Interesting. Is the date and time on your server set correctly? It probably is, but let's rule it out.

**Comment by Smiggel** [comment]
Yes, the date and time are correct.

I think perhaps my underlaying OS is perhaps the problem. I run Raspberry Pi OS Bullseye. On top of that I run OpenMediaVault 6. 

Just now I removed everything related to spotweb. Did a new install in docker, with a stack. I ran the install.php script. When I verify my usenet connecting, I get a blank screen. When I skip the verification, I can continue. However, when I reach the last step, I get a blank again. dbsettings.inc.php is also not created on my disk. Manually creating the dbsettings.inc.php file works and can connect Spotweb.

**Comment by jgeusebroek** [comment]
The underlying OS "shouldn't" have an impact on the docker container. I unfortunately don't have any ideas left.

**Comment by Smiggel** [comment]
Thanks anyway for the help. :-)

**Comment by Smiggel** [comment]
Issue is closed, but I just want to let you know, the issue seems somewhere in your image. I switched to erikdevries/rpi-spotweb docker image and SSL connection works there.

Is perhaps your docker image not ment for a Raspberry Pi?

**Comment by proddy** [comment]
yup, for years now

**Comment by nomnomnomhb** [comment]
I was encountering the same issue today with a fresh deployment on Raspberry Pi OS (Latest, Docker latest). Fixed by updating all packages inside the docker container ... This updated a ton of packages but not the OpenSSL package (I tried solely this package first, but remained the same version).

`docker exec spotweb apt-get update
docker exec spotweb apt-get upgrade -y`

**Comment by Smiggel** [comment]
> I was encountering the same issue today with a fresh deployment on Raspberry Pi OS (Latest updated OS, Docker latest). Fixed by updating all packages inside the spotweb docker container ... This updated a ton of packages but not the OpenSSL package (I tried solely this package first, but remained the same version). Might help someone!
> 
> `docker exec spotweb apt-get update` `docker exec spotweb apt-get upgrade -y`
> 
> (With "spotweb" in the commands as name of your container)

Yes, that’s it! I just now tried it and ask works again! Thank you!
