### ISSUE TITLE
http hardcoded verwijzigingen

### ISSUE THREAD

**Issue by jboesh** [jgeusebroek/docker-spotweb#44]
Hi ik heb spotweb draaiend maar krijg een website te zien zonder opmaak (zie screenshot). maar kan bepaalde dingen ook niet doen, zoals inloggen.
als ik naar de achterkant kijk (in de browser, rechtermuisklik en dan inspecteren) zie ik allerlei http foutmeldingen.
kan het zijn dat je hardcoded http verwijzingen in je code maakt?
met mijn reserved proxy probeer ik alle http requests te redirecten naar https maar de foutmeldingen blijven helaas.

is dit iets je kan oplossen?
wellicht is er een mogelijkheid dat je https kan aanklikken tijdens de install.php?

![image](https://user-images.githubusercontent.com/71582854/145230635-703e05d5-bb05-4ffb-9b1c-18667b52e5a9.png)

```
Mixed Content: The page at 'https://spotweb.mijnwebsite.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://spotweb.mijnwebsite.com/?page=statics&type=css&mod=1637407713'. This request has been blocked; the content must be served over HTTPS.

spotweb.mijnwebsite.com/:40 Mixed Content: The page at 'https://spotweb.mijnwebsite.com/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://spotweb.mijnwebsite.com/?'. This endpoint should be made available over a secure connection.

spotweb.mijnwebsite.com/:1 Mixed Content: The page at 'https://spotweb.mijnwebsite.com/' was loaded over HTTPS, but requested an insecure script 'http://spotweb.mijnwebsite.com/?page=statics&type=js&lang=en_US&mod=1637407713'. This request has been blocked; the content must be served over HTTPS.
(index):249 Uncaught ReferenceError: initSpotwebJs is not defined
    at (index):249
(anoniem) @ (index):249

spotweb.mijnwebsite.com/:1 Mixed Content: The page at 'https://spotweb.mijnwebsite.com/' was loaded over HTTPS, but requested an insecure favicon 'http://spotweb.mijnwebsite.com/?page=statics&type=ico&mod=1637407713'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by jgeusebroek** [comment]
Hi, dit is niet gerelateerd aan de docker image. Het is vrij eenvoudig op te lossen in je reverse proxy.
Zie: https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting#using-a-seperate-ssl-proxy

Succes!

**Comment by jboesh** [comment]
die extra header lijkt niet te werken (proxy_set_header X-SSL 'on';)
dus ik probeer nu de andere suggestie met ownsettings.php 

de spotweb instance draait al, moet ik dat bestand alleen aanmaken met de volgende inhoud?

```
<?php
   $settings['ssloverride'] = true;
?>
```

is dat het enige of staat er meer in? zo ja, heb je daar een voorbeeld van?

**Comment by jboesh** [comment]
is opgelost door de ownsettings.php! bedankt
