### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection timed out/ during install page 2

### ISSUE THREAD

**Issue by professordave** [jgeusebroek/docker-spotweb#47]
Hello, I have tried installing using different methods.
I always seem to get 
SQLSTATE[HY000] [2002] Connection timed out

on
/install.php?page=2

I am on a synology dsm 920+ 7.0.1-42218 Update 3

This is the first guide that I followed, then I uninstalled and tried using the method described here where I run the docker command directly 

tried this first
https://drfrankenstein.co.uk/2022/02/03/spotweb-in-docker-on-synology-nas-coming-soon/

then the 2 step from this wiki

I am able to connect to the mariadb with other db tools, like phpmyadmin.

Mariadb version
1:10.7.3+maria~focal

How can I troubleshoot this?

If I mount a directory 
docker/spotweb       /config

an empty 
ownsettings.php file is created, its size is 0

Thanks in advance

**Comment by jgeusebroek** [comment]
Sorry, this is kind of outside the scope of the image. Spotweb can't talk to the database, this could be for a number of reasons.

When connecting to Mariadb with phpmyadmin, is PHPMyadmin running on the same machine in a docker container?

ownsettings.php being empty is normal.

**Comment by professordave** [comment]
Thank you for the prompt reply.

I am not sure if I tried that. Running phpmyadmin in the same same docker group

I will do that next

**Comment by professordave** [comment]
I think I may have gotten past this.
