### ISSUE TITLE
New build: exec /entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by Smiggel** [jgeusebroek/docker-spotweb#48]
I had to do a new build today for my Pi3 and Pi4 that both run OMV. 

After the rebuild on both systems, I get the following errors in the logs:

> exec /entrypoint.sh: exec format error

Are there not ARM builds available?

**Comment by jgeusebroek** [comment]
There should have been. I forced a new build, this should work; let me know.

**Comment by Smiggel** [comment]
Thanks! That was quick. It's running again after doing a new build!
