### ISSUE TITLE
mysql port

### ISSUE THREAD

**Issue by belsander** [jgeusebroek/docker-spotweb#5]
Hi!

For starters, thanks for the docker image of spotweb, running great on my NAS! I however needed to tweak it a little since spotweb assumes you run your mysql db on 3306. I have opened the following issue: https://github.com/spotweb/spotweb/issues/321

If I get approval, can I push the changes through for your dockerized spotweb here?

Thx!

**Comment by jgeusebroek** [comment]
Pull requests are always appreciated! thanks :)
