### ISSUE TITLE
No images and site looks weird

### ISSUE THREAD

**Issue by zeroquinc** [jgeusebroek/docker-spotweb#50]
Hi, 

First of all thanks for this docker image. I had some trouble setting it up but now it works and I can add it to Prowlarr with the API key.
The whole docker is behind Traefik.
But somehow my whole website looks like this:

![image](https://user-images.githubusercontent.com/39315068/199711781-a1804a57-03aa-4b98-bf4a-4272c1cf737c.png)

I deleted cache, tried diff PC / browser.

I can change settings, but when I save I get this error.

![image](https://user-images.githubusercontent.com/39315068/199712183-6c24d6f5-5cdf-4856-a5f2-52de9123ac8f.png)

Could you give me a hand in the right direction? Thanks !

UPDATE: The site looks normal if I force http instead of https.. hmm

**Comment by jgeusebroek** [comment]
https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting
This should get you up an running.

Good luck!
