### ISSUE TITLE
Eweka cannot connect - Temporary failure in name resolution

### ISSUE THREAD

**Issue by stefaanbolle** [jgeusebroek/docker-spotweb#52]
I do not succeed to connect to Eweka.
Docker is running on QNAP via container station using the provided docker-compose file. It used to work but after a reinstall due to a mariadb crash, I can't get the eweka connection up anymore

The error I get is:
`Retrieving new Spots from server news.eweka.nl...
PHP Warning:  stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729
PHP Warning:  stream_socket_client(): Unable to connect to ssl://news.eweka.nl:563 (php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution) in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729
SpotWeb v0.68.34.34 on PHP v8.0.27 crashed
`

How to resolve?

**Comment by stefaanbolle** [comment]
FYI, I tried apt update in the container but also get the name resolution error.
DNS in the container does not seam to be working

**Comment by jgeusebroek** [comment]
DNS resolving is done by docker; there seems to be a configuration problem on the docker host.

**Comment by stefaanbolle** [comment]
Will reboot the server and test again. Thanks already!

**Comment by stefaanbolle** [comment]
Reboot made it work, so there was a container station issue. No only spots from today are retrieved even if I put history to 1/11/2009. Investigating further but already a working install again :-)

**Comment by jgeusebroek** [comment]
Glad it works! Have a nice day!
