### ISSUE TITLE
Can't connect (and retrieve) to eweka newsserver

### ISSUE THREAD

**Issue by Z0tteke** [jgeusebroek/docker-spotweb#57]
I installed spotweb through docker compose. During installation i choose Eweka as a newsserver. With my credentials i couldn't get the verification to work so i skipped it. After installation i went into the settings and added the eweka settings manually. 
I tried:

```
news.eweka.nl / no encryption / port 110
ssl.eweka.nl / enabled encryption / port 443
ssl.eweka.nl / enabled encryption / port 563
```

None of them was able to retrieve posts.
When i check the log i see the following line:

`PHP Warning:  stream_socket_client(): Unable to connect to ssl://sslreader.eweka.nl:563 (php_network_getaddresses: getaddrinfo for sslreader.eweka.nl failed: Temporary failure in name resolution) in /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php on line 729`

I know my credentials are right because i copy pasted them right from my password manager + the ssl one on port 563 is working within nzbget.

**Comment by jgeusebroek** [comment]
It has trouble resolving the IP address. This is a local docker (host) issue and not an issue with the image. 
Sorry, but I don't have the time to help you with this.
