### ISSUE TITLE
Can't retrieve full history of spots

### ISSUE THREAD

**Issue by Rebelder** [jgeusebroek/docker-spotweb#59]
Hi there,
I've been using your docker image on a Syno NAS and have just moved it to a Ubuntu server (22.04). In both cases I have been unable to retrieve the full history of spots in the config>settings>retrieve part of Spotweb. I'm wondering if it's me or if there is an underlying issue.
<img width="628" alt="Screenshot 2023-04-17 at 17 36 23" src="https://user-images.githubusercontent.com/131011052/232537491-287ac13a-aa30-46f7-aeac-451ee2b72f09.png">

Steps I'm taking:
1. go to retrieve settings
2. choose date 24-11-2010 (also tried it with 01-08-2022, same result)
3. click "change"
4. click "retrieve" in maintenance

After that, only the latest spots are retrieved, not older ones.

Hope you can help, either by redirecting my query somewhere else or investigating it.

**Comment by rb2k5** [comment]
This worked for me - 
https://drfrankenstein.co.uk/spotweb-not-backfilling/

**Comment by Rebelder** [comment]
Thanks a lot for the response, unfortunately I don't seem to be capable enough to execute either of the options. There is no upgrade.php (or upgrade-db.php) in either the spotweb docker or the mariaDB docker. Using PHPMyAdmin I haven't been able to connect to the DB (yet).
@rb2k5 Can you maybe shed some light on the first solution you've given? Where should I find this php script, if it's not in the /bin folder?

**Comment by Rebelder** [comment]
Update: actually both options worked (I had 2 instances of spotweb running)! Thanks a bunch @rb2k5
