### ISSUE TITLE
Nice to have: big nzb button

### ISSUE THREAD

**Issue by zaadstra** [jgeusebroek/docker-spotweb#60]
Hi,

Great image, works perfect.  Only thing that would be nice to have is a big(ger) nzb button, like the blue one on nzbserver dot com.
Is there any way I can hack this in?

Thanks ;-)

**Comment by jgeusebroek** [comment]
You could create your own image based on my image and change the source code. It's not something I will be adding to the image.

Thanks for the suggestion!
