### ISSUE TITLE
(502) Authentication rejected [response: "Too many connections"] [response: ""]

### ISSUE THREAD

**Issue by Suspect-byte** [jgeusebroek/docker-spotweb#62]
Hello,
Everything works amazing except on 1 thing. Spotweb is sending nzbs to my nzbget. That works but as soon I want to add multiple in queue I'm getting this error:

SpotWeb v0.68.34.34 on PHP v8.1.22 crashed
Fatal error occured while connecting to the newsserver:
  (502) Authentication rejected [response: "Too many connections"] [response: ""]

#0 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(143): Services_Nntp_Engine->connect()
#1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(118): Services_Nntp_Engine->selectGroup()
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(298): Services_Retriever_Base->connect()
#3 /var/www/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
#4 {main}

Then I have to wait till my download is fully complete and we can download 1 again. So nothing works when I want to put it in queue.
My newsserver is eweka and I got at least 50 connections. So I don't understand the problem maybe someone can help me?

Thanks in advance!

**Comment by CptChaos** [comment]
The error you are getting is a database error. Lately I am getting the same "Too many connections" issue as well as other issues.

**Comment by jgeusebroek** [comment]
Actually it's not a database error but an error from your newsserver provider. Spotweb can't connect to the newsserver provider because there are already too many connections at once. Most, of not all, providers limit the amount of connections.
