### ISSUE TITLE
Latest docker image not working on older NAS, kernel issue?

### ISSUE THREAD

**Issue by Raytestrak** [jgeusebroek/docker-spotweb#63]
Since the new update, Spotweb won't start anymore, my log says:

Action 'configtest' failed.
[Sun Jan 07 20:31:49.168999 2024] [:crit] [pid 53] (38)Function not implemented: AH00141: Could not initialize random number generator

a quick google search leads me to believe it could be caused my Synology DS416play's kernel is too old (3.10.108): 

"it looks like Apache expects a kernel function to be there, that isn't necessarily there with every kernel"

When I revert to the dev image, Spotweb starts fine.

**Comment by jgeusebroek** [comment]
Thanks for reporting, I will have a look. I upgraded to Ubuntu 22.04 which has a newer apache.

**Comment by Raytestrak** [comment]
Thanks, it's working again. I've checked all my running containers to see if I have working Ubuntu 22 based containers. Most are alpine because that's supposed to be more lightweight, but I have two 22.04 based containers. Maybe it'll help:

Container Name: mariadb, Image: mariadb:latest, OS: Ubuntu 22.04.3 LTS
Container Name: kodi, Image: matthuisman/kodi-headless:Nexus, OS: Ubuntu 22.04.2 LTS


________________________________
