### ISSUE TITLE
Daily cronjob not working?

### ISSUE THREAD

**Issue by Larsvb0** [jgeusebroek/docker-spotweb#64]
Hi I added the line as per the manual:
	-e 'SPOTWEB_CRON_RETRIEVE=*/15 * * * *' \	

this works. Every 15 minutes spotweb updates.

If I change it to 
	-e 'SPOTWEB_CRON_RETRIEVE=*/30 * * * *' \	
or
	-e 'SPOTWEB_CRON_RETRIEVE=*/45 * * * *' \	
it works as well.

If I want it to update daily at a specific time it does not work. For example:
-e 'SPOTWEB_CRON_RETRIEVE=30 13 * * *' \
Nothing happens at 13:30

Console:
root@spotweb:/# crontab -l
30 13 * * * su -l www-data -s /usr/bin/php /var/www/spotweb/retrieve.php >/var/log/stdout 2>&1
root@spotweb:/# date
Sun Jan 14 13:21:13 CET 2024

I used https://crontab.guru/#30_13_*_*_*  for the expression.

any ideas?

**Comment by jgeusebroek** [comment]
Maybe the timezone is different in de docker container?

**Comment by Larsvb0** [comment]
I am adding this:
e 'TZ=Europe/Amsterdam' \

console returns this:
root@spotweb:/# date
Sun Jan 14 13:21:13 CET 2024

This should be ok right?

**Comment by jgeusebroek** [comment]
Yes that should be correct. Weird, I don't have an explanation. Is there a /var/log/cron?
TBH I don't use the cron feature myself. I run cron on the host.

`*/15 * * * * docker exec spotweb su -l www-data -s /usr/bin/php /var/www/spotweb/retrieve.php >/dev/null 2>&1`

**Comment by Larsvb0** [comment]
Ok let me try that

**Comment by Larsvb0** [comment]
weird, If i run this on the host nothing happens:

*/1 * * * * docker exec spotweb su -l www-data -s /usr/bin/php /var/www/spotweb/retrieve.php >/dev/null 2>&1

running crontab -l gives me No crontab for User

How do I configure this?

**Comment by Larsvb0** [comment]
nevermind I got it I had to enable crontab for the user first.

Here are the steps:
crontab -e
choose 2

install Vim using:
sudo apt-get update
sudo apt-get install vim

vim crontab
add this line: */15 * * * * docker exec spotweb su -l www-data -s /usr/bin/php /var/www/spotweb/retrieve.php >/dev/null 2>&1
hit ESC, type :x to save the file
