### ISSUE TITLE
Include postgresql driver

### ISSUE THREAD

**Issue by neographikal** [jgeusebroek/docker-spotweb#8]
SPOTWEB_DB_TYPE=pdo_pgsql

Gives:
Unable to connect to database: 
could not find driver 

Could the postgres driver be included?

**Comment by jgeusebroek** [comment]
Added! 7f73460e783a573aa28148e304baa2f56629cdca.

**Comment by rayures** [comment]
tnx! 

tip: it should be mentioned in the readme.md that postgresql extension also is available.
